### ISSUE TITLE
No field for the entity ID (Pid, Lid, or Qid) on Entity struct?

### ISSUE THREAD

**Issue by dashstander** [Smittyvb/wikidata#1]
Perhaps I'm missing something obvious, but once you've created an Entity struct is there a way to get the wikidata ID for it?

**Comment by dashstander** [comment]
I'm pretty new to Rust, so this may not be particularly clean or idiomatic, but I added a field to the Entity struct in [this branch](https://github.com/dashstander/wikidata/tree/add_entity_id). Would you mind if I made a PR?

**Comment by Smittyvb** [comment]
Yep, that looks good, committed as e9cd90efff208ac82923fe59de93a724cb7117e1. I adjusted the change a little bit by running `cargo fmt` on it and simplifying the `get_wiki_id_test` test a little bit:
```diff
     #[test]
     fn get_wiki_id_test() {
-        match get_wiki_id(&"Q42") {
-            Ok(id) => {
-                assert_eq!(id, WikiId::EntityId(Qid(42)));
-            }
-            _ => return (),
-        }
+        assert_eq!(get_wiki_id("Q42").unwrap(), WikiId::EntityId(Qid(42)));
     }
```

**Comment by dashstander** [comment]
Awesome, thanks so much! And thanks for putting this crate together, it's made working with the Wikidata dumps an absolute breeze :)
